port: 5344
services:
  - name: webdav
    root_dir: "./davroot"
    username: "abc"
    password: "123"
    mode: "readwrite"

  - name: mydav
    root_dir: "./davroot"
    username: "abc"
    password: "123"
    mode: "readwrite"
